# Radioisotope Thermoelectric Generator (RTG) Metadata

# =============================================================================
# IDENTITY
# =============================================================================

id: rtg
name: Radioisotope Thermoelectric Generator
short_description: >
  Converts heat from radioactive decay (primarily Pu-238) directly into
  electricity via the Seebeck effect, providing decades of reliable power
  with no moving parts.

# =============================================================================
# FACETS
# =============================================================================

facets:
  ultimate_source: nuclear
  conversion_pathway: direct_electrical
  theoretical_limit: carnot
  temporal_character: baseload
  geographic_constraint: global
  scale_regime: site_limited
  material_criticality: fuel_dependent

# =============================================================================
# COMPARISON DATA
# =============================================================================

comparison_data:

  theoretical_limit:
    name: Carnot limit (thermoelectric conversion)
    value_percent: 55
    achieved_percent: 6
    applies_to: Heat to electricity via Seebeck effect
    notes: >
      Carnot limit ~55% for typical RTG temperatures (1273K hot, 573K cold).
      Actual thermoelectric efficiency 5-7% due to material ZT limitations.
      Low efficiency acceptable because decay heat is continuous and waste
      heat warms spacecraft systems.

  power_density:
    peak_w_per_m2: null
    average_w_per_m2: null
    delivered_w_per_m2: null
    notes: >
      Pu-238 specific thermal power: 0.56 W/g. MMRTG: 110-125 W electrical
      from 4.8 kg PuO₂ fuel (45 kg total mass). Power-to-mass ratio ~2.5 W/kg.
      Voyager RTGs still operating after 47+ years at ~47% original power.

  current_status:
    trl: 9
    lcoe_range_usd_mwh: null
    global_capacity_gw: 0.000001
    annual_growth_percent: null
    notes: >
      Mature technology (60+ years, 27+ missions). Current US standard: MMRTG
      (110 W). Total US Pu-238 inventory ~35 kg. Production restarted 2015 at
      Oak Ridge, targeting 1.5 kg/year. Cost ~$109 million per MMRTG unit.
      Next-gen RTG (~250 W) targeted for 2030.

  temporal:
    diurnal: false
    seasonal_variation: none
    predictability: high
    dispatchable: false
    notes: >
      Continuous power output, declining ~1-2%/year from fuel decay and
      thermocouple degradation. Pu-238 half-life 87.7 years; after 14 years
      ~90% thermal power remains. Cannot be turned off or modulated.

# =============================================================================
# RELATIONSHIPS
# =============================================================================

related:
  - id: nuclear-fission
    relationship: shares_source
  - id: thermoelectrics
    relationship: shares_conversion_pathway

# =============================================================================
# KEY EQUATIONS
# =============================================================================

equations:
  - id: pu238_decay
    latex: ^{238}_{94}Pu \rightarrow ^{234}_{92}U + ^{4}_{2}He + 5.6 \text{ MeV}
    description: Plutonium-238 alpha decay releasing 5.6 MeV per event

  - id: seebeck_voltage
    latex: V = S \cdot \Delta T
    description: Voltage generated by Seebeck effect (S = Seebeck coefficient)

  - id: thermoelectric_zt
    latex: ZT = \frac{S^2 \sigma T}{\kappa}
    description: Thermoelectric figure of merit (higher ZT = better material)

  - id: carnot_efficiency
    latex: \eta_{Carnot} = 1 - \frac{T_c}{T_h}
    description: Maximum theoretical efficiency for heat engine
