# Wind Energy Metadata

# =============================================================================
# IDENTITY
# =============================================================================

id: wind
name: Wind Energy
short_description: >
  Converts kinetic energy from atmospheric air motion into electricity via
  aerodynamic lift on rotating turbine blades coupled to generators.

# =============================================================================
# FACETS
# =============================================================================

facets:
  ultimate_source: solar
  conversion_pathway: mechanical_intermediate
  theoretical_limit: betz
  temporal_character: weather_driven
  geographic_constraint: global
  scale_regime: arbitrarily_modular
  material_criticality: variant_dependent

# =============================================================================
# COMPARISON DATA
# =============================================================================

comparison_data:

  theoretical_limit:
    name: Betz limit
    value_percent: 59.3
    achieved_percent: 47
    applies_to: Kinetic energy extraction from open fluid flow
    notes: >
      Real turbines achieve 45-50% peak Cp (75-85% of Betz limit).
      Glauert limit accounting for wake rotation gives 53-57% at typical tip-speed ratios.

  power_density:
    peak_w_per_m2: 1200
    average_w_per_m2: 400
    delivered_w_per_m2: 3
    notes: >
      Peak is for exceptional offshore sites (wind power density >1200 W/m2).
      Average is for good sites. Delivered is farm-level output per total land area
      (1-7 W/m2 range, typically 2-3 W/m2). Only 1-3% of wind farm land is
      actually occupied by infrastructure.

  current_status:
    trl: 9
    lcoe_range_usd_mwh: [20, 79]
    global_capacity_gw: 1136
    annual_growth_percent: 11
    notes: >
      Onshore LCOE $20-34/MWh (global average $34/MWh).
      Offshore fixed LCOE $50-79/MWh.
      Offshore floating LCOE $150-300/MWh (declining rapidly).
      2024 installations: 117 GW (record year). 83 GW offshore total.

  temporal:
    diurnal: false
    seasonal_variation: moderate
    predictability: moderate
    dispatchable: false
    notes: >
      Output varies with weather on timescales from seconds (turbulence) to
      seasons (many regions have stronger winter winds). Capacity factors:
      onshore 25-45% (avg 36%), offshore 35-55% (avg 41%), best sites >50%.

# =============================================================================
# RELATIONSHIPS
# =============================================================================

related:
  - id: offshore-wind
    relationship: variant
  - id: tidal-stream
    relationship: shares_theoretical_limit

# =============================================================================
# KEY EQUATIONS
# =============================================================================

equations:
  - id: wind_power
    latex: P_{wind} = \frac{1}{2} \rho A v^3
    description: Power available in wind flowing through cross-sectional area A

  - id: betz_limit
    latex: C_{p,max} = \frac{16}{27} \approx 0.593
    description: Maximum extractable fraction of wind power (Betz-Joukowsky limit)

  - id: wind_shear
    latex: v(z) = v_{ref} \left(\frac{z}{z_{ref}}\right)^\alpha
    description: Wind speed variation with height (power law approximation)
